export const APPLICANT_LOGIN = "APPLICANT_LOGIN";
export const APPLICANT_LOCATION_DATA = "APPLICANT_LOCATION_DATA";
export const APPLICANT_DETAILS = "APPLICANT_DETAILS";
export const APPLICANT_SIGNUP = "APPLICANT_SIGNUP";
export const RECRUITER_DASHBOARD_TOP10 = "RECRUITER_DASHBOARD_TOP10";
export const PROFILE_VIEWS = "PROFILE_VIEWS";
